// console.log("Hello world")
// console.log("goodbey")
// console.log("Hello".length)
// console.log("hello".toUpperCase())
//console.log(Math.floor(Math.random()*10))
console.log("|  |")
console.log("|  |")
console.log("|  |")
console.log(".....")
console.log("|   |")
console.log("|   |")  
console.log("|   |")
console.log(".....")
console.log("|   |")
console.log("|   |")
console.log("|   |")
console.log("All aroundtthe would"[7].toUpperCase())
